# Generated by Django 4.1.3 on 2023-02-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="wa_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
