# Generated by Django 4.1 on 2022-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.CharField(
                default=1, max_length=120, verbose_name="GitHub Profile"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Student"), (2, "Coach"), (3, "Manager"), (4, " ")],
                default=1,
                verbose_name="Role",
            ),
        ),
    ]
