# Generated by Django 4.1 on 2022-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Profile'),
        ),
    ]
