# Generated by Django 4.1 on 2022-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '__first__'),
        ('users', '0004_remove_user_github_user_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(to='achievements.achievement'),
        ),
    ]
