# Generated by Django 4.1.1 on 2022-10-09 08:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_user_phone_user_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Student"), (2, "Coach")],
                default=1,
                verbose_name="User Type",
            ),
        ),
    ]
