version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: up-study-db
    env_file:
      - .env
    ports:
      - 5942:5432

volumes:
  postgres_data:
