# Generated by Django 4.1.2 on 2022-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("resume", "0003_alter_language_options_alter_resume_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Section Name")),
                ("description", models.TextField(verbose_name="Section Description")),
            ],
            options={
                "verbose_name_plural": "Section",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Course Name")),
                ("description", models.TextField(verbose_name="Course Description")),
                ("published", models.BooleanField()),
                ("images", models.ManyToManyField(to="base.image")),
                (
                    "programming_languages",
                    models.ManyToManyField(to="resume.programminnglanguage"),
                ),
                ("section", models.ManyToManyField(to="courses.section")),
            ],
        ),
    ]
