# Generated by Django 4.1.3 on 2023-01-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Language")),
                ("code", models.CharField(max_length=120, verbose_name="Name Code")),
            ],
            options={
                "verbose_name_plural": "Language",
            },
        ),
        migrations.CreateModel(
            name="ProgramminngLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, verbose_name="Name of the Programming Language"
                    ),
                ),
                ("code", models.CharField(max_length=120, verbose_name="Name Code")),
            ],
            options={
                "verbose_name_plural": "Programming Language",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=120, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Last Name"),
                ),
                ("about_me", models.TextField(verbose_name="About Me")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="locations.city",
                    ),
                ),
                ("language", models.ManyToManyField(to="resume.language")),
                (
                    "programming_language",
                    models.ManyToManyField(to="resume.programminnglanguage"),
                ),
            ],
            options={
                "verbose_name_plural": "Resume",
            },
        ),
    ]
