# Generated by Django 4.1 on 2022-09-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudyProgramming",
        ),
        migrations.AlterModelOptions(
            name="programminnglanguage",
            options={"verbose_name_plural": "Programming Language"},
        ),
        migrations.RemoveField(
            model_name="resume",
            name="user",
        ),
    ]
