# Generated by Django 4.1.1 on 2022-10-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_delete_studyprogramming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Resume'},
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='resume.country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
    ]
