name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    needs:
      - linter
      - tests
      - check-migrations
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEV_DESTINATION }}
            docker-compose up --build -d
