name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |

        curl -sSL https://install.python-poetry.org | python -
        poetry install

    - name: Lint with flake8
      run: |
        flake8 src/ --exclude=migrations,__pycache__ --max-line-length 120

    - name: Run Tests
      run: |
        pytest
