name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: |

        curl -sSL https://install.python-poetry.org | python -
        poetry install
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  linter:
    name: Linter
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: flake8 src/ --exclude=migrations,__pycache__ --max-line-length 120 --ignore=F401,F403,F405

  tests:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: pytest

  check-migrations:
    name: Check Migrations
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: |
        upstudy makemigrations --dry-run --check

  open-api:
    name: Create Schema
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: create schema.yml
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - run: |
        DJANGO_SETTINGS_MODULE=src.upstudy.spectacular_settings upstudy spectacular --file schema.yml

    - name: create schema.yml
      uses: actions/upload-artifact@v3
      with:
        name: open-api-schema
        path: schema.yml

